name: Update Dashboard Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"   # ogni 3 ore

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update metrics JSON
        env:
          GA4_SERVICE_ACCOUNT_JSON: ${{ secrets.GA4_SERVICE_ACCOUNT_JSON }}
          GA4_PROPERTY_ID: ${{ secrets.GA4_PROPERTY_ID }}
          ADSENSE_CLIENT_ID: ${{ secrets.ADSENSE_CLIENT_ID }}
          ADSENSE_CLIENT_SECRET: ${{ secrets.ADSENSE_CLIENT_SECRET }}
          ADSENSE_REFRESH_TOKEN: ${{ secrets.ADSENSE_REFRESH_TOKEN }}
          ADSENSE_ACCOUNT_ID: ${{ secrets.ADSENSE_ACCOUNT_ID }}
        run: |
          python -m scripts.update_metrics

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.146.0"
          extended: true

      - name: Theme (PaperMod)
        run: |
          rm -rf themes/PaperMod
          git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod themes/PaperMod

      - name: Build
        run: |
          hugo --minify -b "https://lfdario.github.io/site-automation-pro/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
