name: Publish Site
on:
  schedule:
    - cron: "0 5 * * *"  # 07:00 Europe/Rome approx
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
  PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     - name: Generate today's posts (2 articles)
  env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  run: |
    python -m scripts.generate_posts --count 2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.133.0'
          extended: true

      - name: Theme
        run: |
          rm -rf themes/ananke
          git clone --depth=1 https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke

      - name: Build
        run: |
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
