name: Publish Site

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"   # 07:00 CET giornaliero
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

 - name: Generate posts
  env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  run: |
    python -m scripts.generate_posts --count 4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.146.0"
          extended: true

      - name: Fetch Hugo theme (PaperMod)
        run: |
          rm -rf themes/PaperMod
          git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod themes/PaperMod

      - name: Build
        run: |
          hugo --minify -b "https://lfdario.github.io/site-automation-pro/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
